print('понедельник', end = ', ') 
print('вторник',  end = ', ') 
print('вторник', end = ', ') 
print('среда', end = ', ')
print('четверг', end = ', ') 
print('пятница', end = ', ') 
print('суббота', end = ', ')
print('воскресенье')